---
- hosts: all
  tasks:
  - name: download k3d
    ansible.builtin.command: curl https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh -o /tmp/installk3d.sh
    args:
      creates: /tmp/installk3d.sh
  - name: install k3d
    ansible.builtin.command: bash /tmp/installk3d.sh
    args:
      creates: /usr/local/bin/k3d
  - name: download helm
    ansible.builtin.command: curl -o /tmp/installhelm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    args:
      creates: /tmp/installhelm.sh
  - name: install helm
    ansible.builtin.command: bash /tmp/installhelm.sh
    args:
      creates: /usr/local/bin/helm
  - name: change permissions on helm
    become: true
    ansible.builtin.file:
      path: /usr/local/bin/helm
      mode: o=x  
  - name: download kubectl
    ansible.builtin.command: curl -Lo /tmp/installkubectl https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl
    args:
      creates: /tmp/installkubectl
      
  - name: install kubectl
    ansible.builtin.command: sudo install -o root -g root -m 0755 /tmp/installkubectl /usr/local/bin/kubectl
    args:
      creates: /usr/local/bin/kubectl

  - name: create auto instrumented wordpress docker image
    community.docker.docker_image:
      name: autoinstrumented-bitnami-wordpress
      source: build
      build:
        path: autoinstrumented-wordpress
        dockerfile: Dockerfile
      
  - name: create cluster
    ansible.builtin.command: k3d cluster create local-k8s
    args:
      creates: ~/.kube/config  

  - name: Load Docker image into k3d cluster
    ansible.builtin.command: k3d image import autoinstrumented-bitnami-wordpress:latest -c local-k8s

  - name: Add OpenTelemetry Helm repository
    kubernetes.core.helm_repository:
      name: open-telemetry
      repo_url: https://open-telemetry.github.io/opentelemetry-helm-charts

  - name: Add Jaeger Helm repository
    kubernetes.core.helm_repository:
      name: jaeger-all-in-one
      repo_url: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/charts

  - name: Install Jaeger
    kubernetes.core.helm:
      name: jaeger
      chart_ref: jaeger-all-in-one/jaeger-all-in-one
      release_namespace: default
      values:
        enableHttpOpenTelemetryCollector: true


  - name: Install OpenTelemetry Collector
    kubernetes.core.helm:
      name: opentelemetry-collector
      chart_ref: open-telemetry/opentelemetry-collector
      release_namespace: default
      values_files:
        - otel-collector-config.yaml
      
  - name: Deploy Wordpress chart from bitnami
    kubernetes.core.helm:
      name: wordpress
      chart_ref: oci://registry-1.docker.io/bitnamicharts/wordpress
      release_namespace: default
      values:
        image:
          repository: autoinstrumented-bitnami-wordpress
          tag: latest
          pullPolicy: Never
          debug: true

       


